# Generated by Django 3.0.3 on 2020-04-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
